package mcptools

import (
	"confluence-mcp-v10.2.14/internal/helpers"
	"context"
	"fmt"
	"github.com/mark3labs/mcp-go/mcp"
	"io"
	"time"
)

// Input Schema for the GetMacroBodyByHash tool
const GetMacroBodyByHashInputSchema = "{\n  \"properties\": {\n    \"hash\": {\n      \"description\": \"the macroId to find the correct macro.\",\n      \"type\": \"string\"\n    },\n    \"id\": {\n      \"description\": \"  the id of the content.\",\n      \"type\": \"string\"\n    },\n    \"version\": {\n      \"description\": \"the version of the content which the hash belongs.\",\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"hash\",\n    \"id\",\n    \"version\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetMacroBodyByHash tool (Status: 200, Content-Type: application/json)
const GetMacroBodyByHashResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Returns a json representation of a macro.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// Response Template for the GetMacroBodyByHash tool (Status: 404, Content-Type: application/json)
const GetMacroBodyByHashResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 404\n\n**Content-Type:** application/json\n\n> Returned if there is no content with the given id, or if the calling user does not have permission to view the content, or there is no macro matching the given hash or id.\n\n## Response Structure\n\n- Structure (Type: unknown):\n"

// NewGetMacroBodyByHashMCPTool creates the MCP Tool instance for GetMacroBodyByHash
func NewGetMacroBodyByHashMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetMacroBodyByHash",
		"Get macro body by hash - Returns the body of a macro (in storage format) with the given hash. This resource is primarily used by connect applications that require the body of macro to perform their work. \n\nThe hash is generated by connect during render time of the local macro holder and is usually only relevant during the scope of one request. For optimisation purposes, this hash will usually live for multiple requests. \n\nCollecting a macro by its hash should now be considered deprecated and will be replaced, transparently with macroIds. This resource is currently only called from connect addons which will eventually all use the "+"\x60"+"getContentById"+"\x60"+" resource. \n\nTo make the migration as seamless as possible, this resource will match macros against a generated hash or a stored macroId. This will allow add ons to work during the migration period.",
		[]byte(GetMacroBodyByHashInputSchema),
	)
}

// GetMacroBodyByHashHandler is the handler function for the GetMacroBodyByHash tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetMacroBodyByHashHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	startTime := time.Now()
	resp, err := mcputils.ForwardRequest(ctx, upstream, "GET", "/confluence/rest/api/content/{id}/history/{version}/macro/hash/{hash}", args, []string{"hash", "id", "version"}, contentType)
	if err != nil {
		return nil, fmt.Errorf("upstream request failed: %w", err)
	}
	defer resp.Body.Close()

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read upstream response: %w", err)
	}

	mcputils.LogResponse(ctx, resp.StatusCode, "GET", resp.Request.URL.String(), time.Since(startTime), body)

	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return mcp.NewToolResultError(fmt.Sprintf("upstream error: status %d, body: %s", resp.StatusCode, string(body))), nil
	}

	if filePath, err := mcputils.SaveBinaryResponse(resp, body, "GetMacroBodyByHash"); err != nil {
		return mcp.NewToolResultError(err.Error()), nil
	} else if filePath != "" {
		return mcp.NewToolResultText(fmt.Sprintf("Saved to: %s (%d bytes)", filePath, len(body))), nil
	}

	return mcp.NewToolResultText(string(body)), nil
}
